import { DEFAULT_LLM_RECOVERY_POLICY } from '../llm-loop/llm-loop-types.js';

/** Shared Inspector fields for provider/tool recovery policy. */
export const llmRecoveryUiSchema = [
	{
		field: 'streamIdleTimeoutMs',
		type: 'number',
		label: 'Stream idle timeout (ms, 0 disables)',
		default: 90000,
		min: 0,
		step: 1,
	},
	{
		field: 'toolTimeoutMs',
		type: 'number',
		label: 'Tool timeout (ms, 0 disables)',
		default: 60000,
		min: 0,
		step: 1,
	},
	{
		field: 'subagentTimeoutMs',
		type: 'number',
		label: 'Sub-Agent timeout (ms, 0 disables)',
		default: DEFAULT_LLM_RECOVERY_POLICY.subagentTimeoutMs,
		min: 0,
		step: 1,
	},
	{
		field: 'maxTransientRetries',
		type: 'number',
		label: 'Transient provider retries',
		default: 2,
		min: 0,
		max: 32,
		step: 1,
	},
	{
		field: 'autokickOnIdle',
		type: 'boolean',
		label: 'Autokick on idle and dead-loop',
		default: DEFAULT_LLM_RECOVERY_POLICY.autokickOnIdle,
	},
	{
		field: 'deadLoopEnabled',
		type: 'boolean',
		label: 'Detect repetition dead loops',
		default: DEFAULT_LLM_RECOVERY_POLICY.deadLoopEnabled,
	},
	{
		field: 'maxAutokickAttempts',
		type: 'number',
		label: 'Max autokick reconnects (0 = unlimited)',
		default: DEFAULT_LLM_RECOVERY_POLICY.maxAutokickAttempts,
		min: 0,
		max: 1000,
		step: 1,
	},
	{
		field: 'autokickBackoffMs',
		type: 'number',
		label: 'Autokick backoff base (ms)',
		default: DEFAULT_LLM_RECOVERY_POLICY.autokickBackoffMs,
		min: 1000,
		step: 1000,
	},
	{
		field: 'autokickMaxBackoffMs',
		type: 'number',
		label: 'Autokick backoff clamp (ms)',
		default: DEFAULT_LLM_RECOVERY_POLICY.autokickMaxBackoffMs,
		min: 1000,
		step: 1000,
	},
	{
		field: 'autokickUserMessage',
		type: 'string',
		label: 'Autokick kick message',
		default: DEFAULT_LLM_RECOVERY_POLICY.autokickUserMessage,
	},
	{
		field: 'autokickPenaltyFrequency',
		type: 'number',
		label: 'Autokick frequency_penalty delta',
		default: DEFAULT_LLM_RECOVERY_POLICY.autokickPenaltyDelta.frequency,
		min: -2,
		max: 2,
		step: 0.1,
	},
	{
		field: 'autokickPenaltyPresence',
		type: 'number',
		label: 'Autokick presence_penalty delta',
		default: DEFAULT_LLM_RECOVERY_POLICY.autokickPenaltyDelta.presence,
		min: -2,
		max: 2,
		step: 0.1,
	},
	{
		field: 'deadLoopMaxWindowTokens',
		type: 'number',
		label: 'Dead-loop window (tokens)',
		default: DEFAULT_LLM_RECOVERY_POLICY.deadLoop.maxWindowTokens,
		min: 10,
		max: 8000,
		step: 1,
	},
	{
		field: 'deadLoopConsecutiveThreshold',
		type: 'number',
		label: 'Dead-loop consecutive identical deltas',
		default: DEFAULT_LLM_RECOVERY_POLICY.deadLoop.consecutiveThreshold,
		min: 1,
		step: 1,
	},
	{
		field: 'deadLoopMinRepetitions',
		type: 'number',
		label: 'Dead-loop cyclic repetitions',
		default: DEFAULT_LLM_RECOVERY_POLICY.deadLoop.minRepetitions,
		min: 1,
		step: 1,
	},
	{
		field: 'deadLoopMinPatternTokens',
		type: 'number',
		label: 'Dead-loop min pattern tokens',
		default: DEFAULT_LLM_RECOVERY_POLICY.deadLoop.minPatternTokens,
		min: 1,
		step: 1,
	},
] as const;
